import { Routes } from "../routes";  
  
  export const navigationData = [
    {
      title: "Customer Management",
      icon:"carbon:id-management" ,
      eventKey: "tables/",
      children: [
        { title: "Dashboard", link: Routes.AddProducts.path },
        { title: "Profile Management", link: Routes.ListProducts.path },
        { title: "Feedback", link: Routes.ListProducts.path },
        { title: "Loyalty Program", link: Routes.ListProducts.path },
        { title: "Query Center", link: Routes.AddProducts.path },
        { title: "Payment and Billing", link: Routes.ListProducts.path },
        { title: "Travel Center", link: Routes.ListProducts.path },
        { title: "Customer Community", link: Routes.ListProducts.path },
        { title: "Customer Education Hub", link: Routes.ListProducts.path },
        { title: "Deals and Discounts", link: Routes.ListProducts.path },
      ]
    },
    {
      title: "Booking Management",
      icon: "carbon:gui-management",
      eventKey: "examples/",
      children: [
        { title: "Hotel Booking", link: Routes.AddSales.path },
        { title: "Flight Booking", link: Routes.ListSales.path },
        { title: "Car Rental Booking", link: Routes.ListSales.path },
        { title: "Tour and Activity", link: Routes.ListSales.path },
        { title: "Multi-Service Package", link: Routes.ListSales.path },
        { title: "Available Calenders", link: Routes.ListSales.path },
        { title: "Payment Process", link: Routes.ListSales.path },
        { title: "Booking Analytics", link: Routes.ListSales.path },
        { title: "Integration and API", link: Routes.ListSales.path },
        { title: "Customer Communication", link: Routes.ListSales.path },
        { title: "Auth and Authorization", link: Routes.ListSales.path },
      ]
    },
    {
      title: "Accounting and Finance",
      icon: "carbon:finance",
      eventKey: "documentation/",
      children: [
        { title: "General Ledger", link: Routes.AddPurchases.path },
        { title: "Budgeting and Forecasting", link: Routes.PurchasesList.path },
        { title: "Tax Management", link: Routes.PurchasesList.path },
        { title: "Financial Reporting", link: Routes.PurchasesList.path },
        { title: "Expense Management", link: Routes.PurchasesList.path },
        { title: "Invoicing", link: Routes.PurchasesList.path },
        { title: "Billing", link: Routes.PurchasesList.path },
        { title: "Payroll Processing", link: Routes.PurchasesList.path },
        { title: "Supplier Evaluation", link: Routes.PurchasesList.path },
        { title: "Deductions", link: Routes.PurchasesList.path },
        { title: "Attendance Tracking", link: Routes.PurchasesList.path },
        { title: "Leave Balances", link: Routes.PurchasesList.path },
        { title: "Financial Compliance", link: Routes.PurchasesList.path },
      ]
    },
    {
      title: "Supplier Management",
      icon: "carbon:finance",
      eventKey: "components/",
      children: [
        { title: "Supplier Collaboration Hub", link: Routes.Customers.path },
        { title: "SP Report", link: Routes.Suppliers.path },
        { title: "Dashboard", link: Routes.Suppliers.path },
        { title: "Listing Management", link: Routes.Suppliers.path },
        { title: "Contract Management", link: Routes.Suppliers.path },
        { title: "Performance Tracking", link: Routes.Suppliers.path },
        { title: "Supplier Database", link: Routes.Suppliers.path },
        { title: "Communication Center", link: Routes.Suppliers.path },
        { title: "Supplier Evaluation", link: Routes.Suppliers.path },
        { title: "Supplier Alerts", link: Routes.Suppliers.path },
        { title: "SP Analytics", link: Routes.Suppliers.path },
        { title: "Contract Alerts", link: Routes.Suppliers.path },
        { title: "Messaging System", link: Routes.Suppliers.path },
      ]
    },
    {
      title: "Communication",
      icon: "material-symbols:communication-rounded",
      eventKey: "components/",
      children: [
        { title: "Dashboard", link: Routes.Customers.path },
        { title: "Customer Notification", link: Routes.Suppliers.path },
        { title: "Customer Support ", link: Routes.Suppliers.path },
        { title: "Supplier Announcement", link: Routes.Suppliers.path },
        { title: "Supplier Messaging", link: Routes.Suppliers.path },
        { title: "Telephony System", link: Routes.Suppliers.path },
        { title: "Live Chat", link: Routes.Suppliers.path },
        { title: "Email Integretion", link: Routes.Suppliers.path },
        { title: "Employee Directory", link: Routes.Suppliers.path },
        { title: "Internal Messaging", link: Routes.Suppliers.path },
        { title: "Announcement Center", link: Routes.Suppliers.path },
      ]
    },
    {
      title: "Human Resources",
      icon: "healthicons:human-resoruces-outline",
      eventKey: "components/",
      children: [
        { title: "Workforce Planning", link: Routes.Customers.path },
        { title: "Health and Safety", link: Routes.Suppliers.path },
        { title: "Employee Recognition", link: Routes.Suppliers.path },
        { title: "Time and Attendance", link: Routes.Suppliers.path },
        { title: "Diversity, Equity andInclusion (DEI)", link: Routes.Suppliers.path },
        { title: "Remote Work Support", link: Routes.Suppliers.path },
        { title: "Employee Records", link: Routes.Suppliers.path },
        { title: "Payroll Management", link: Routes.Suppliers.path },
        { title: "Leave and Attendance", link: Routes.Suppliers.path },
        { title: "Recruitment and Onboard", link: Routes.Suppliers.path },
        { title: "Performance Management", link: Routes.Suppliers.path },
        { title: "Training and Development", link: Routes.Suppliers.path },
        { title: "Employee Engagement", link: Routes.Suppliers.path },
        { title: "Benefits Administration", link: Routes.Suppliers.path },
        { title: "Employee Engagement", link: Routes.Suppliers.path },
        { title: "Benefits Administration", link: Routes.Suppliers.path },
        { title: "Employee Self-Service", link: Routes.Suppliers.path },
        { title: "HR Analytics and Reporting", link: Routes.Suppliers.path },
        { title: "Succession Planning", link: Routes.Suppliers.path },
        { title: "Compliance Management", link: Routes.Suppliers.path },
        { title: "Compliance Management", link: Routes.Suppliers.path },
      ]
    },
  ];